// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtterlyComplete.Infrastructure.Data.Contexts;

#nullable disable

namespace UtterlyComplete.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("UtterlyComplete.Domain.Core.ContactMechanism", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("ContactMechanisms", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ContactMechanism");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Core.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<int>("FacilityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PartOfFacilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SquareFootage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FacilityTypeId");

                    b.HasIndex("PartOfFacilityId");

                    b.ToTable("Facilities", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Facility");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Core.FacilityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FacilityType", (string)null);
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Core.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("Parties", (string)null);
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Core.PartyContactMechanism", b =>
                {
                    b.Property<int>("PartyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContactMechanismId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("NonSolicitationIndicator")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ThruDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PartyId", "ContactMechanismId", "FromDate");

                    b.HasIndex("ContactMechanismId");

                    b.ToTable("PartyContactMechanism", (string)null);
                });

            modelBuilder.Entity("UtterlyComplete.Domain.ContactMechanisms.ElectronicAddress", b =>
                {
                    b.HasBaseType("UtterlyComplete.Domain.Core.ContactMechanism");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ElectronicAddressString");

                    b.ToTable("ContactMechanisms", (string)null);

                    b.HasDiscriminator().HasValue("ElectronicAddress");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.ContactMechanisms.PostalAddress", b =>
                {
                    b.HasBaseType("UtterlyComplete.Domain.Core.ContactMechanism");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("TEXT");

                    b.ToTable("ContactMechanisms", (string)null);

                    b.HasDiscriminator().HasValue("PostalAddress");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.ContactMechanisms.TelecommunicationsNumber", b =>
                {
                    b.HasBaseType("UtterlyComplete.Domain.Core.ContactMechanism");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.ToTable("ContactMechanisms", (string)null);

                    b.HasDiscriminator().HasValue("TelecommunicationsNumber");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Facilities.AmbulatorySurgeryCenter", b =>
                {
                    b.HasBaseType("UtterlyComplete.Domain.Core.Facility");

                    b.HasDiscriminator().HasValue("AmbulatorySurgeryCenter");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Facilities.Clinic", b =>
                {
                    b.HasBaseType("UtterlyComplete.Domain.Core.Facility");

                    b.HasDiscriminator().HasValue("Clinic");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Facilities.Floor", b =>
                {
                    b.HasBaseType("UtterlyComplete.Domain.Core.Facility");

                    b.HasDiscriminator().HasValue("Floor");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Facilities.Hospital", b =>
                {
                    b.HasBaseType("UtterlyComplete.Domain.Core.Facility");

                    b.HasDiscriminator().HasValue("Hospital");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Facilities.MedicalBuilding", b =>
                {
                    b.HasBaseType("UtterlyComplete.Domain.Core.Facility");

                    b.HasDiscriminator().HasValue("MedicalBuilding");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Facilities.MedicalOffice", b =>
                {
                    b.HasBaseType("UtterlyComplete.Domain.Core.Facility");

                    b.HasDiscriminator().HasValue("MedicalOffice");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Facilities.Room", b =>
                {
                    b.HasBaseType("UtterlyComplete.Domain.Core.Facility");

                    b.HasDiscriminator().HasValue("Room");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Core.ContactMechanism", b =>
                {
                    b.HasOne("UtterlyComplete.Domain.Core.Facility", null)
                        .WithMany("ContactMechanisms")
                        .HasForeignKey("FacilityId");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Core.Facility", b =>
                {
                    b.HasOne("UtterlyComplete.Domain.Core.FacilityType", "FacilityType")
                        .WithMany("Facilities")
                        .HasForeignKey("FacilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtterlyComplete.Domain.Core.Facility", "PartOfFacility")
                        .WithMany("ConsistsOfFacilities")
                        .HasForeignKey("PartOfFacilityId");

                    b.Navigation("FacilityType");

                    b.Navigation("PartOfFacility");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Core.Party", b =>
                {
                    b.HasOne("UtterlyComplete.Domain.Core.Facility", null)
                        .WithMany("Parties")
                        .HasForeignKey("FacilityId");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Core.PartyContactMechanism", b =>
                {
                    b.HasOne("UtterlyComplete.Domain.Core.ContactMechanism", null)
                        .WithMany("PartyContactMechanisms")
                        .HasForeignKey("ContactMechanismId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtterlyComplete.Domain.Core.Party", null)
                        .WithMany("PartyContactMechanisms")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Core.ContactMechanism", b =>
                {
                    b.Navigation("PartyContactMechanisms");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Core.Facility", b =>
                {
                    b.Navigation("ConsistsOfFacilities");

                    b.Navigation("ContactMechanisms");

                    b.Navigation("Parties");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Core.FacilityType", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("UtterlyComplete.Domain.Core.Party", b =>
                {
                    b.Navigation("PartyContactMechanisms");
                });
#pragma warning restore 612, 618
        }
    }
}
